name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or the version you prefer

      - name: Install Dependencies
        run: npm install

      - name: Build project
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
        with:
          build_dir: ./dist
